[mypy]
python_version = 3.9
files = pymarginstv.py, stvtree.py, stvdistance.py, utils.py
check_untyped_defs = True
no_implicit_optional = True
warn_unused_ignores = True

[mypy-pyscipopt.*]
ignore_missing_imports = True
